name = "C25-challenge"
uuid = "9cf41daa-8b23-44cd-8361-13903e21d1fd"
authors = ["Lucas Igel"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
